/* Generated By:JJTree: Do not edit this line. ASTAdviceExecutionPointcut.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTAdviceExecutionPointcut extends SimpleNode {
  public ASTAdviceExecutionPointcut(int id) {
    super(id);
  }

  public ASTAdviceExecutionPointcut(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b0e252afcdf27088d2d65fff17f52926 (do not edit this line) */
