/* Generated By:JJTree: Do not edit this line. ASTArrayTypePatternExpression.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

public class ASTArrayTypePatternExpression extends SimpleNode {
    
    public ASTArrayTypePatternExpression(final int id) {
        super(id);
    }
    
    public ASTArrayTypePatternExpression(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public int arrayDimension;
    
    public int getArrayDimension() {
        return this.arrayDimension;
    }
    
}
/* JavaCC - OriginalChecksum=7746030b63c78f70660d1d32a696cd16 (do not edit this line) */
