/* Generated By:JJTree: Do not edit this line. ASTBoolean.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTBoolean extends SimpleNode implements PrimitiveType {
    
    public ASTBoolean(final int id) {
        super(id);
    }
    
    public ASTBoolean(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "boolean";
    }
    
}
/* JavaCC - OriginalChecksum=be2736aa2cf8d071085be43ef0544d11 (do not edit this line) */
