/* Generated By:JJTree: Do not edit this line. ASTBaseTypePattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTBaseTypePattern extends SimpleNode {
  public ASTBaseTypePattern(int id) {
    super(id);
  }

  public ASTBaseTypePattern(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0834dae3d3c84fbe9b1af4961aa7e3e7 (do not edit this line) */
