/* Generated By:JJTree: Do not edit this line. ASTByte.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTByte extends SimpleNode implements PrimitiveType {
    
    public ASTByte(final int id) {
        super(id);
    }
    
    public ASTByte(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "byte";
    }
    
}
/* JavaCC - OriginalChecksum=11e1f274d92b858b4e8a24da080ec731 (do not edit this line) */
