/* Generated By:JJTree: Do not edit this line. ASTBasicClassnamePattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTBasicClassnamePattern extends SimpleNode {
  public ASTBasicClassnamePattern(int id) {
    super(id);
  }

  public ASTBasicClassnamePattern(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b1838df951db5f594c9748bf67362682 (do not edit this line) */
