/* Generated By:JJTree: Do not edit this line. ASTCallPointcut.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTCallPointcut extends SimpleNode {
  public ASTCallPointcut(int id) {
    super(id);
  }

  public ASTCallPointcut(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9905b75ffc9ec6bf18862a298ff91d72 (do not edit this line) */
