/* Generated By:JJTree: Do not edit this line. ASTCflowbelowPointcut.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTCflowbelowPointcut extends SimpleNode {
  public ASTCflowbelowPointcut(int id) {
    super(id);
  }

  public ASTCflowbelowPointcut(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c3339c3ce2385f8ebe7f0ec36275cef (do not edit this line) */
