/* Generated By:JJTree: Do not edit this line. ASTConstructorPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTConstructorPattern extends SimpleNode {
  public ASTConstructorPattern(int id) {
    super(id);
  }

  public ASTConstructorPattern(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=13c5192f6cf58b49bf83fcf2c2df1d24 (do not edit this line) */
