/* Generated By:JJTree: Do not edit this line. ASTDouble.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTDouble extends SimpleNode implements PrimitiveType {
    
    public ASTDouble(final int id) {
        super(id);
    }
    
    public ASTDouble(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "double";
    }
    
}
/* JavaCC - OriginalChecksum=3a0bf73e0b35afbe156c45c294b8bce1 (do not edit this line) */
