/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

public class ASTIdentifier extends SimpleNode {
    
    public ASTIdentifier(final int id) {
        super(id);
    }
    
    public ASTIdentifier(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String identifier;
    
    public String getIdentifier() {
        return this.identifier;
    }
    
}
/* JavaCC - OriginalChecksum=e420c8ffc48b393d975addb7de254ca2 (do not edit this line) */
