/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTInt extends SimpleNode implements PrimitiveType {
    
    public ASTInt(final int id) {
        super(id);
    }
    
    public ASTInt(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "int";
    }
    
}
/* JavaCC - OriginalChecksum=c287b3aefd3b8adee137d3f8221c9e23 (do not edit this line) */
