/* Generated By:JJTree: Do not edit this line. ASTLong.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTLong extends SimpleNode implements PrimitiveType {
    
    public ASTLong(final int id) {
        super(id);
    }
    
    public ASTLong(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "long";
    }
    
}
/* JavaCC - OriginalChecksum=b1f12e10b5c1b26afd6c74ff285a0ef4 (do not edit this line) */
