/* Generated By:JJTree: Do not edit this line. ASTOrClassnamePatternExpressionNobang.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTOrClassnamePatternExpressionNobang extends SimpleNode {
  public ASTOrClassnamePatternExpressionNobang(int id) {
    super(id);
  }

  public ASTOrClassnamePatternExpressionNobang(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=280e46ee6a1c40dd003374b299fd5f48 (do not edit this line) */
