/* Generated By:JJTree: Do not edit this line. ASTOrPointcutExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTOrPointcutExpression extends SimpleNode {
  public ASTOrPointcutExpression(int id) {
    super(id);
  }

  public ASTOrPointcutExpression(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=60d4118d70caedd6e1eb945eb1956931 (do not edit this line) */
