/* Generated By:JJTree: Do not edit this line. ASTOrClassnamePatternExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTOrClassnamePatternExpression extends SimpleNode {
  public ASTOrClassnamePatternExpression(int id) {
    super(id);
  }

  public ASTOrClassnamePatternExpression(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c60781775549d8b49bca68b194dbe574 (do not edit this line) */
