/* Generated By:JJTree: Do not edit this line. ASTOrTypePatternExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTOrTypePatternExpression extends SimpleNode {
  public ASTOrTypePatternExpression(int id) {
    super(id);
  }

  public ASTOrTypePatternExpression(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a146cfb42742c1953dd1f501cb5b1c8e (do not edit this line) */
