/* Generated By:JJTree: Do not edit this line. ASTPreinitializationPointcut.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTPreinitializationPointcut extends SimpleNode {
  public ASTPreinitializationPointcut(int id) {
    super(id);
  }

  public ASTPreinitializationPointcut(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=81a0e1dc480f5be8b01f861027ee2029 (do not edit this line) */
