/* Generated By:JJTree: Do not edit this line. ASTShort.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTShort extends SimpleNode implements PrimitiveType {
    
    public ASTShort(final int id) {
        super(id);
    }
    
    public ASTShort(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "short";
    }
    
}
/* JavaCC - OriginalChecksum=d5e0621a73572572470fbb50912d13e8 (do not edit this line) */
