/* Generated By:JJTree: Do not edit this line. ASTStaticinitializationPointcut.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTStaticinitializationPointcut extends SimpleNode {
  public ASTStaticinitializationPointcut(int id) {
    super(id);
  }

  public ASTStaticinitializationPointcut(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1603d703fc766b855fd93f23313fcc95 (do not edit this line) */
