/* Generated By:JJTree: Do not edit this line. ASTTypeArgumentList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTTypeArgumentList extends SimpleNode {
  public ASTTypeArgumentList(int id) {
    super(id);
  }

  public ASTTypeArgumentList(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5b84c818d007d6ef98f4505f4d409c7 (do not edit this line) */
