/* Generated By:JJTree: Do not edit this line. ASTTypeIdStarList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTTypeIdStarList extends SimpleNode {
  public ASTTypeIdStarList(int id) {
    super(id);
  }

  public ASTTypeIdStarList(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=371bc8bb1875663a2af581366a41e089 (do not edit this line) */
