/* Generated By:JJTree: Do not edit this line. ASTUnknownBoundedTypeArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTUnknownBoundedTypeArgument extends SimpleNode {
  public ASTUnknownBoundedTypeArgument(int id) {
    super(id);
  }

  public ASTUnknownBoundedTypeArgument(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f0b21d529751ba9ae55982e06fad1a1 (do not edit this line) */
