/* Generated By:JJTree: Do not edit this line. ASTVoid.java Version 4.1 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=
 */
package org.alia4j.aspectj.parser.ast;

import org.alia4j.aspectj.parser.PrimitiveType;

public class ASTVoid extends SimpleNode implements PrimitiveType {
    
    public ASTVoid(final int id) {
        super(id);
    }
    
    public ASTVoid(final AJPointcutParser p, final int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(final AJPointcutParserVisitor visitor, final Object data) {
        return visitor.visit(this, data);
    }
    
    public String getTypeName() {
        return "void";
    }
    
}
/* JavaCC - OriginalChecksum=8b2d0595370c4a612038c8a97454cdca (do not edit this line) */
