/* Generated By:JJTree: Do not edit this line. ASTWildcardBoundsSuper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTWildcardBoundsSuper extends SimpleNode {
  public ASTWildcardBoundsSuper(int id) {
    super(id);
  }

  public ASTWildcardBoundsSuper(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fbf7b769aa611b7c23c2e29e1a1d33e4 (do not edit this line) */
