/* Generated By:JJTree: Do not edit this line. ASTWildcardBoundsExtends.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.alia4j.aspectj.parser.ast;

public
class ASTWildcardBoundsExtends extends SimpleNode {
  public ASTWildcardBoundsExtends(int id) {
    super(id);
  }

  public ASTWildcardBoundsExtends(AJPointcutParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AJPointcutParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57535ba8f79077a8ebe31042d69ede3e (do not edit this line) */
